version: "3.8"

services:
  database:
    image: mysql:8.0
    container_name: mysqldb
    networks:
      - chatapp-network
    environment:
      MYSQL_ROOT_PASSWORD: "admin123"
      MYSQL_DATABASE: "chatappdb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin123"
    volumes:
      - chatapp-db-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend-server
    networks:
      - chatapp-network
    environment:
      DB_NAME: "chatappdb"
      DB_USER: "admin"
      DB_PASSWORD: "admin123"
      DB_HOST: "mysqldb"
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend-nginx
    networks:
      - chatapp-network
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  chatapp-network:
    driver: bridge

volumes:
  chatapp-db-volume:

